### PR TITLE
Rename property ExtensionData to Extensions

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by leastprivilege** [comment]
You previous PRs produced some invalid code comments - could you fix that first?

**Comment by vanillajonathan** [comment]
My bad, I fixed it now.

**Comment by leastprivilege** [comment]
there are still warnings...

**Comment by vanillajonathan** [comment]
Hmm, where?

**Comment by leastprivilege** [comment]
Scroll down here
https://github.com/IdentityModel/IdentityModel/pull/417/files

**Comment by vanillajonathan** [comment]
My bad, I fixed that, I missed those, I didn't notice those warnings among all the other warnings. My bad.

**Comment by leastprivilege** [comment]
thanks

**Pull request merged**
