### PR TITLE
Avoid allocation for Identity.Anonymous

### PR DESCRIPTION
**Pull request by ghost**
Currently, each access to `Identity.Anonymous` allocates a new `ClaimsIdentity`. This PR avoid the allocation by storing the `ClaimsIdentity` in a static field.

Before:

| Method | Mean       | Error     | StdDev    | Gen0        | Allocated |
|------- |-----------:|----------:|----------:|------------:|----------:|
| A      |   1.403 ms | 0.0090 ms | 0.0080 ms |   2218.7500 |   4.43 MB |
| B      | 135.194 ms | 1.6368 ms | 1.4510 ms | 221750.0000 | 442.51 MB |

After:

| Method | Mean       | Error     | StdDev    | Allocated |
|------- |-----------:|----------:|----------:|----------:|
| A      |   3.022 us | 0.0216 us | 0.0192 us |         - |
| B      | 289.792 us | 1.0158 us | 0.9005 us |         - |

Benchmark code:
```cs
[MemoryDiagnoser]
public class Bench
{
    [Benchmark]
    public void A()
    {
        for (int i = 0; i < 10_000; i++)
        {
            var a = Identity.Anonymous;
        }
    }

    [Benchmark]
    public void B()
    {
        for (int i = 0; i < 1_000_000; i++)
        {
            var a = Identity.Anonymous;
        }
    }
}
```

### CODE REVIEW

**Comment by msschl** [comment]
It is quite strange to return a new instance on each call to the property getter. If this is intentional it should better be a method instead of a property. Otherwise this refactor looks reasonable.

**Comment by leastprivilege** [comment]
Well - the problem is that it can be altered after retrieved. This would have side effect.

**Comment by msschl** [comment]
That's why a property is wired to me. It should probably be a method

**Comment by leastprivilege** [comment]
It is what it is ;)

**Pull request closed without merging**
